qsub job1.csh -q dybtuningq
qsub job2.csh -q dybtuningq
qsub job3.csh -q dybtuningq
qsub job4.csh -q dybtuningq
qsub job5.csh -q dybtuningq
qsub job6.csh -q dybtuningq
qsub job7.csh -q dybtuningq
qsub job8.csh -q dybtuningq
qsub job9.csh -q dybtuningq
qsub job10.csh -q dybtuningq
qsub job11.csh -q dybtuningq
qsub job12.csh -q dybtuningq
qsub job13.csh -q dybtuningq
qsub job14.csh -q dybtuningq
qsub job15.csh -q dybtuningq
qsub job16.csh -q dybtuningq
qsub job17.csh -q dybtuningq
qsub job18.csh -q dybtuningq
qsub job19.csh -q dybtuningq
qsub jobCo1.csh -q dybtuningq
qsub jobCo2.csh -q dybtuningq
qsub jobGe.csh -q dybtuningq
qsub jobCs.csh -q dybtuningq
qsub jobH.csh -q dybtuningq
qsub jobK.csh -q dybtuningq
qsub job_nC1.csh -q dybtuningq
qsub job_nC2.csh -q dybtuningq
qsub job_nC3.csh -q dybtuningq
qsub job_nC4.csh -q dybtuningq
qsub job_nC5.csh -q dybtuningq
qsub job_nC6.csh -q dybtuningq
