{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Jun 19 07:33:00 2013) by ROOT version5.26/00e
   TCanvas *c1 = new TCanvas("c1", "c1",342,530,700,500);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   c1->Range(-15.28378,-90.78072,102.2838,665.7253);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLeftMargin(0.13);
   c1->SetRightMargin(0.13);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.12);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *eIntervalTime = new TH1F("eIntervalTime","eIntervalTime",400,0,400);
   eIntervalTime->SetBinContent(6,1);
   eIntervalTime->SetBinContent(7,2);
   eIntervalTime->SetBinContent(8,26);
   eIntervalTime->SetBinContent(9,154);
   eIntervalTime->SetBinContent(10,206);
   eIntervalTime->SetBinContent(11,409);
   eIntervalTime->SetBinContent(12,587);
   eIntervalTime->SetBinContent(13,598);
   eIntervalTime->SetBinContent(14,525);
   eIntervalTime->SetBinContent(15,525);
   eIntervalTime->SetBinContent(16,484);
   eIntervalTime->SetBinContent(17,395);
   eIntervalTime->SetBinContent(18,347);
   eIntervalTime->SetBinContent(19,285);
   eIntervalTime->SetBinContent(20,222);
   eIntervalTime->SetBinContent(21,166);
   eIntervalTime->SetBinContent(22,145);
   eIntervalTime->SetBinContent(23,144);
   eIntervalTime->SetBinContent(24,97);
   eIntervalTime->SetBinContent(25,88);
   eIntervalTime->SetBinContent(26,62);
   eIntervalTime->SetBinContent(27,33);
   eIntervalTime->SetBinContent(28,31);
   eIntervalTime->SetBinContent(29,22);
   eIntervalTime->SetBinContent(30,10);
   eIntervalTime->SetBinContent(31,8);
   eIntervalTime->SetBinContent(32,4);
   eIntervalTime->SetBinContent(33,3);
   eIntervalTime->SetBinContent(34,3);
   eIntervalTime->SetBinContent(35,1);
   eIntervalTime->SetEntries(5583);
   
   TPaveStats *ptstats = new TPaveStats(0.6681034,0.7478814,0.8692529,0.9470339,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetLineWidth(2);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(132);
   TText *text = ptstats->AddText("Entries = 5583   ");
   ptstats->SetOptStat(10);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   eIntervalTime->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(eIntervalTime->GetListOfFunctions());
   eIntervalTime->SetLineWidth(2);
   eIntervalTime->SetMarkerStyle(6);
   eIntervalTime->GetXaxis()->SetRange(1,87);
   eIntervalTime->GetXaxis()->SetLabelFont(132);
   eIntervalTime->GetXaxis()->SetLabelOffset(0.01);
   eIntervalTime->GetXaxis()->SetLabelSize(0.05);
   eIntervalTime->GetXaxis()->SetTitleSize(0.05);
   eIntervalTime->GetXaxis()->SetTitleFont(132);
   eIntervalTime->GetYaxis()->SetLabelFont(132);
   eIntervalTime->GetYaxis()->SetLabelOffset(0.01);
   eIntervalTime->GetYaxis()->SetLabelSize(0.05);
   eIntervalTime->GetYaxis()->SetTitleSize(0.05);
   eIntervalTime->GetYaxis()->SetTitleOffset(1.1);
   eIntervalTime->GetYaxis()->SetTitleFont(132);
   eIntervalTime->GetZaxis()->SetLabelFont(132);
   eIntervalTime->GetZaxis()->SetLabelOffset(0.01);
   eIntervalTime->GetZaxis()->SetLabelSize(0.05);
   eIntervalTime->GetZaxis()->SetTitleSize(0.05);
   eIntervalTime->GetZaxis()->SetTitleOffset(1.1);
   eIntervalTime->GetZaxis()->SetTitleFont(132);
   eIntervalTime->Draw("");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
